kasibara/kasibara/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('word_cloud.urls'))
]

kasibara/word_cloud/urls.py
from django.urls import path

from .models import Lyric
from . import views

app_name = "word_cloud"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('add-lyric', views.AddLyricView.as_view(), name="add_lyric"),
    path('lyric-detail/<int:pk>/',
         views.lyricDetailView.as_view(), name="lyric_detail"),
]

kasibara/word_cloud/models.py
from django.db import models
from wordcloud import WordCloud
import spacy
import io
import base64
from PIL import Image

FONT_PATH = "/usr/share/fonts/opentype/ipaexfont-gothic/ipaexg.ttf"


class Lyric(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=150)
    released_at = models.DateTimeField(verbose_name="発表年", null=True)
    lyricist = models.CharField(verbose_name="作詞", max_length=100, null=True)
    composer = models.CharField(verbose_name="作曲", max_length=100, null=True)
    singer = models.CharField(verbose_name="歌手", max_length=100, null=True)
    content = models.TextField(verbose_name="本文", null=True)
    word_cloud_img = models.ImageField(verbose_name="ワードクラウド", null=True)

    class Meta:
        verbose_name_plural = "Lyric"

    def __str__(self):
        return self.title


def get_word_cloud(text):
    nlp = spacy.load('ja_ginza')
    doc = nlp(text)

    noun_toks = []
    for tok in doc:
        noun_toks.append(tok)
    wc = WordCloud(font_path=FONT_PATH,
                   max_font_size=40).generate(" ".join(map(lambda tok: tok.text, noun_toks)))

    buffer = io.BytesIO()
    image_array = wc.to_array()
    img = Image.fromarray(image_array)
    img.save(buffer, format="PNG")
    base64Img = base64.b64encode(
        buffer.getvalue()).decode().replace("'", "")

    return base64Img

kasibara/word_cloud/forms.py
from django import forms
from .models import Lyric
import datetime

today = datetime.date.today()


class AddLyricForm(forms.ModelForm):
    released_at = forms.DateTimeField(
        label='発表年',
        input_formats=['%Y'],
        widget=forms.DateInput(
            format='%Y',
            attrs={'placeholder': 'YYYY'}))

    class Meta:
        model = Lyric
        fields = ('__all__')
        exclude = ('word_cloud_img',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control mx-5 my-2"

kasibara/word_cloud/views.py
from django.urls.base import reverse, reverse_lazy
from django.views import generic
from .forms import AddLyricForm
from .models import Lyric
from .models import get_word_cloud
from django.shortcuts import render


class IndexView(generic.ListView):
    model = Lyric
    template_name = "index.html"


class AddLyricView(generic.CreateView):
    model = Lyric
    template_name = "add_lyric.html"
    form_class = AddLyricForm
    success_url = reverse_lazy("word_cloud:index")


class lyricDetailView(generic.DetailView):
    model = Lyric
    template_name = 'lyric_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        target = Lyric.objects.filter(pk=self.kwargs['pk']).first()
        context['wc_img_base64'] = get_word_cloud(target.content)
        return context

kasibara/word_cloud/templates/add_lyric.html
{% extends 'base.html' %}
{% load static %}
{% block title %}カシバラ{% endblock %}
{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>カシバラ</h1>
                    <span class="subheading">カシがバラバラ</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="my-5">
                    <form id="contactForm" method="POST">
                        {% csrf_token %}
                        <table class="myFormTable">
                            {{ form.as_table }}
                        </table>
                        <br />
                        <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

kasibara/word_cloud/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>カシバラ</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
        rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- My style-->
    <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'word_cloud:index' %}">KASIBARA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                            href="{% url 'word_cloud:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                            href="{% url 'word_cloud:add_lyric' %}">Add Lyric</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% block header %}{% endblock %}
    {% block contents %}{% endblock %}
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

kasibara/word_cloud/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}カシバラ{% endblock %}
{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>カシバラ</h1>
                    <span class="subheading">カシがバラバラ</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% for lyric in lyric_list %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'word_cloud:lyric_detail' lyric.pk %}">
                    <h2 class="post-title">{{ lyric.title }}</h2>
                    <h3 class="post-subtitle">{{ lyric.content | truncatechars:20 }}</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on September 24, 2021
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% empty %}
            <p>歌詞が登録されていません</p>
            {% endfor %}
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts
                    →</a></div>
        </div>
    </div>
</div>
{% endblock %}

kasibara/word_cloud/templates/lyric_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}カシバラ{% endblock %}
{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>カシバラ</h1>
                    <span class="subheading">カシがバラバラ</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<!-- Main Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h2 class="section-heading">{{ object.title }}</h2>
                <p>{{ object.content|linebreaksbr }}</p>
                <img src="data:image/png;base64,{{wc_img_base64}}" />
            </div>
        </div>
    </div>
</article>
{% endblock %}